services:
  app:
    restart: always
    depends_on:
      - db
    build:
      dockerfile: ../Dockerfile
      context: app/
    networks:
      - lawly_db
    env_file:
      - app/.env
    ports:
      - "8801:80"

  db:
    image: postgres:14.5
    restart: always
    networks:
      - lawly_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./lawly_db_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

networks:
  lawly_db:
