services:
  prod-app:
    restart: always
    build:
      dockerfile: ../Dockerfile
      context: app/
    networks:
      - lawly_prod_db
    env_file:
      - app/.env
    ports:
      - "8821:80"

networks:
  lawly_prod_db:
    external: true
